spring.application.name=autsub

# database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/autsub
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate configuration for SQL logs 
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type=trace



security.jwt.secret-key=9acd2521770636ae273e44a021909777c83731d0682d236dfccdd5361c6d5f98
security.jwt.expiration-time=3600000


logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.http.converter=DEBUG